# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Подкаст из провинции
subtitle: обычные разговоры ни о чём
email: eugene.suchkov@gmail.com
author: Eugene Suchkov
keywords: [personal, blog, New York]
itunes_categories: [Personal Journals]
explicit: 'no'
language: ru
license: CC BY-NC-SA 3.0
description: > # this means to ignore newlines until "baseurl:"
  Это такой аудиодневник или, можно сказать, колыбельная для друзей. Впрочем, заходите на огонек
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cityhawk.ru" # the base hostname & protocol for your site
twitter_username: cityhawk
github_username:  CityHawk

# Build settings
markdown: kramdown
